forbidden_tags = [
    {"name": "style"},
    {"name": "script"},
    {"name": "span", "class": "IPA"},
    {"name": "span", "$and": [{"class": "unicode"}, {"class": "haudio"}]},
    {"name": "span", "class": "mw-editsection"},
    # {"name": "table", "$and": [{"class": "infobox"}, {"class": "vcard"}]},
    {"name": "div", "$and": [{"class": "infobox"}, {"class": "sisterproject"}]},
    {"name": "sup", "class": "reference"},
    {"name": "div", "role": "navigation"},
    {"name": "table"},
    {"name": "span", "$and": [{"class": "error"}, {"class": "mw-ext-cite-error"}]},
    {"name": "div", "$and": [{"class": "boilerplate"}, {"class": "metadata"}, {"class": "plainlinks"}]},
    {"name": "figure"},
    {"name": "div", "role": "note"},
    {"name": "title"},
    {"name": "annotation", "encoding": "application/x-tex"},
]

new_line_tags = [
    "p",
    "br",
    "hr",
    "li",
    "ol",
    "dl",
    "dt",
    "dd",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
]
